### ISSUE TITLE
Rlon vs lon  &  Viewing the data 

### ISSUE THREAD

**Issue by brittpetershydro** [Ouranosinc/ESPO-G#1]
Hello @tlogan2000 

Two questions for you:
1) I noticed there are 2 different latitude variables ("rlat" and "lat") and 2 different longitude variables ("rlon" and "lon").  What is the difference between these variables?  Do I need the rlon and rlat for anything?

2) When viewing the data (which was sub-setted using a bounding box with lat_bnds=[45,48], lon_bnds=[-80,-72]), I noticed there are a bunch of NaN values. Please see my .jpg file attached - the figure on the left used the "pcolor" matlab function to view the data, whereas the figure on the right used the "imagesc" matlab function.  Focusing on the figure on the left, I can see that the grids extend past my specified lat_bnds and lon_bnds and put in a bunch of "NaN" values.  Any idea why this happens?     Also, is there a reason why the data appears to be rotated when I use the "imagesc" function? When dealing with temperature, it is relatively easy to tell when the data is rotated, but with precipitation it would be more difficult to tell.

![GitHub - Data Viewing Q](https://github.com/Ouranosinc/ESPO-G/assets/136091329/22082a77-a407-4965-9cfb-65e8199755d8)

**Comment by aulemahal** [comment]
Hi @brittpetershydro,

The reference dataset (RDRS v2.1) comes on a "rotated pole" grid. The X and Y coordinates are called "rlon" and "rlat" and are _rotated_ in comparison to the "real" longitude and latitude. This is often done in models to remove the longitudinal contraction of the grid cells near Earth's poles.  I plotted the grid of RDRS (Rotated Pole) on a "Plate Carrée" map (where a 1°x1° square of the "real" longitude latitude plots as a perfect square):

![image](https://github.com/Ouranosinc/ESPO-G/assets/20629530/c59626e9-aa65-49fa-a352-7962d53713a3)

Thus, ESPO-G6-R2 is generated on that grid. We re-project the model output (that comes in all sorts of grids, not only the regular lat/lon) towards this grid as one of the first step of the workflow. (In fact, we do it in many steps to avoid artefacts stemming from the large resolution jump).

In the data, you have both coordinates. You'll notice that `rlat` and `rlon` are 1D, as they are the primary coordinates of the data. `lon` and `lat` are given, but as 2D maps. When you subsetted the data with a regular lat/lon bounding box, the function still gave you a data rectangle back. You got back the smallest rotated pole rectangle that includes the requested lat/lon rectangle. Data outside your zone was masked with NaNs.

Matlab's `pcolor` seems to have understood that the plot axes should be lat and lon, and thus gave a "plate carrée" view with the rotated grid and your requested rectangle seen "upright".  However, `imagesc` doesn't seem to understand the data coordinates at all and just plotted using the raw coordinates. The X axis seems to be "rlat" and the Y, "rlon". This fits the data on disk which has "rlat" as its first dimension and "rlon" in second. `imagesc` also doesn't seem to understand what NaNs are, this is also problematic...

In python, we usually use `xESMF` to transform grids. If you need to work on a regular lat/lon grid, you could use that package, regridding ESPO-G6-R2 to the grid of your choice. The package is available on PAVICS. I'm sure there are Matlab tools to do that, but I personally don't know them.

**Comment by brittpetershydro** [comment]
Thank you for your explanation of the rotated pole, and explaining how the bounding box for sub-setting works. This is very helpful!

With pcolor I actually have to specify latitude and longitude manually, so it makes sense that it displayed correctly using that function. It seems to me that if we use matlab, pcolor is the better option...  But out of curiosity, is there a way in PAVICS to make the "rlon" the first dimension and "rlat" the second dimension prior to outputting to a netCDF file?

**Comment by tlogan2000** [comment]
> is there a way in PAVICS to make the "rlon" the first dimension and "rlat" the second dimension prior to outputting to a netCDF file?

@brittpetershydro using something like `ds.transpose('time', 'rlon', 'rlat')`  (or other preferred order) before writing to netcdf should do the trick

**Comment by brittpetershydro** [comment]
@tlogan2000 I tried ds.transpose and the data ended up upside down.

**Comment by aulemahal** [comment]
@brittpetershydro `imagesc` plots the "y" axis from top to bottom. What if you try to `set(gca,'YDir','normal')` ?

**Comment by brittpetershydro** [comment]
Sorry for my delayed response.   Thank you, we are able to process into a format that we need.
